create table BenhNhan(
MABENHNHAN CHAR(5),
SOPHIEU VARCHAR(10),
HOTEN VARCHAR(225),
ID_BENHAN VARCHAR(10),
NAMSINH INT,
DIACHI VARCHAR(525),
KHOADIEUTRI VARCHAR(50),
NGAYVAODIEUTRI DATE,
NGAYRAVIEN DATE,
KETQUADIEUTRI VARCHAR(225),
CHANDOANBENH VARCHAR(225),
BIENCHUNGBENH VARCHAR(225),
CONSTRAINT PK_BenhNhan PRIMARY KEY (MABENHNHAN));

